spring:
  datasource:
    url: ${url}
    username: ${usr}
    password: ${pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      maximumPoolSize: 10
#      minimumIdle: 2
#      maxLifetime: 120000
#      idleTimeout: 60000 # 1 minutes
#      keepaliveTime: 15000
#      validation-timeout: 3000
      max-lifetime: 300000
      idle-timeout: 120000
      keepalive-time: 45000
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: "SELECT 1"
      connectionInitSql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
  data:
    redis:
      url: ${REDIS_URL:redis://default:nQZGarDxzUTiLOCawvBOQkNHCjhmzRGh@caboose.proxy.rlwy.net:57131}
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.5-flash
      embedding:
        options:
          model: text-embedding-004
    vector-store:
      redis:
        index: faq_idx
        prefix: faq
    retry:

  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    properties:
      security:
        protocol: PLAINTEXT
      client:
        dns:
          lookup: use_all_dns_ips
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.fa25se225.capstone.dto.kafka"

brevo:
  api-key: ${BREVO_API_KEY}
  sender:
    name: "APCertificate"
    email: "diep.tranc@gmail.com"
  templates:
    VERIFY_EMAIL: 1
    TEMPORARY_PASSWORD: 7
    RESET_PASSWORD_OTP: 8
    ACCOUNT_LOCKED: 9

outbound:
  oauth2:
    client-id: ${OAUTH2_CLIENT_ID:aaaaaaaa}
    client-secret: ${OAUTH2_CLIENT_SECRET:aaaaaaaa}
    redirect-uri: ${OAUTH2_REDIRECT_URI}
    grant-type: "authorization_code"
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration-in-second: 36000
  refreshable-duration-in-second: 36000
  issuer: "Tri dep trai"

cloudinary:
  cloud-name: ${cloud}
  api-key: ${API_KEY}
  api-secret: ${secret}

server:
  port : 8080
  forward-headers-strategy : native
minio:
  url: ${url-minio}
  access-key: ${access-key}
  secret-key: ${secret-key}
  bucket:
    avatars: avatars
    materials: materials
    lesson : lesson
  bucket-video: video-lessons

momo:
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  endpoint: https://payment.momo.vn/v2/gateway/api/create
  redirect-url: https://capstoneproject-production-857f.up.railway.app/loading
  ipn-url: https://fa25se225capstone-production.up.railway.app/edcare/api/v1/payment/momo/ipn


