spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FA25SE225_Capstone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.fa25se225.capstone.dto.kafka.NotificationEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

brevo:
  api-key: ""
  sender:
    name: "edcare"
    email: "dovantri1709@gmail.com"
  templates:
    OTP_VERIFICATION: 1
    FORGOT_PASSWORD: 2