spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FA25SE225_Capstone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9094

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

brevo:
  api-key: "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"
  sender:
    name: "edcare"
    email: "dovantri1709@gmail.com"
  templates:
    OTP_VERIFICATION: 1
    FORGOT_PASSWORD: 2